version: "3.9"
services:
  webapp:
    image: drupal
    ports:
    - "8080:80"
    volumes:
    - drupal-modules:/var/www/html/modules \
    - drupal-profiles:/var/www/html/profiles \
    - drupal-sites:/var/www/html/sites \
    - drupal-themes:/var/www/html/themes \

db:

  image: postgres
  environment: 
    POSTGRES_PASSWORD: example
  volumes:
  - mydb: /var/lib/postgresql/data

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:



